name: Continuous Integration Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  windows-build:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Create build directory and run CMake
        shell: cmd
        run: |
          cmake -S . -B cmake_build_dir -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=cmake_install_dir
      - name: Build project
        run: |
          cmake --build cmake_build_dir --target ALL_BUILD --config Debug
          cmake --build cmake_build_dir --target ALL_BUILD --config Release
      - name: Run tests
        run:  ctest -C Release -VV
        working-directory: cmake_build_dir
      - name: Install project
        run: |
          cmake --build cmake_build_dir --target INSTALL --config Debug
          cmake --build cmake_build_dir --target INSTALL --config Release
      - name: Create Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Windows-Artifacts
          path: cmake_install_dir/
        if: always()

  ubuntu-build:
    name: Ubuntu Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Create build directory and run CMake
        run: |
          sudo apt-get -y update
          sudo apt-get -y install freeglut3-dev
          cmake -S . -B cmake_build_dir -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=cmake_install_dir
      - name: Build project
        run: |
          cmake --build cmake_build_dir --target install --config Release
      - name: Run tests
        run:  ctest -C Release -VV
        working-directory: cmake_build_dir
      - name: Create Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Ubuntu-Artifacts
          path: cmake_install_dir/
        if: always()

#  macos-build:
#    name: MacOS Build
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Checkout submodules
#        run: git submodule update --init --recursive
#      - name: Create build directory and run CMake
#        run: |
#          cmake -S . -B cmake_build_dir -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=cmake_install_dir
#      - name: Build project
#        run: |
#          cmake --build cmake_build_dir --target install --config Release -- -j4
#      - name: Run tests
#        run: ctest -C Release -VV
#        working-directory: cmake_build_dir
#      - name: Create Artifacts
#        uses: actions/upload-artifact@v1
#        with:
#          name: MacOS-Artifacts
#          path: cmake_install_dir/
#        if: always()
